#!/usr/bin/env bash
# Display information about subdomains.

dns_record() {
  local full_domain="$1"
  local subdomain="$2"

  local result
  local record_type
  result=$(dig "$full_domain" +short | awk 'NR==1{print}')
  record_type=$(dig "$full_domain" +noall +answer | awk '{print $4}' | head -1)

  if [[ -n "$result" && -n "$record_type" ]]; then
    echo "The subdomain $subdomain is a $record_type record and points to $result"
  fi
}

domain="$1"
subdomain="$2"

if [ "$#" == 1 ]; then
  subdomain_list=("www" "lb-01" "web-01" "web-02")
  for sub in "${subdomain_list[@]}"; do
    dns_record "$sub.$domain" "$sub"
  done
elif [ "$#" == 2 ]; then
  dns_record "$subdomain.$domain" "$subdomain"
fi
