#!/usr/bin/env bash
# Install and configure HAproxy on ubuntu server.

# Update and install HAproxy
sudo apt -y update
sudo apt-get install -y haproxy


# Add frontend and backend configuration to HAProxy
sudo bash -c 'cat >> /etc/haproxy/haproxy.cfg' <<EOF

# Frontend
frontend http_front
    bind *:80
    default_backend web_servers

# Backend
backend web_servers
    balance roundrobin
    option httpchk
    server web-01 54.144.249.38 check
    server web-02 54.90.63.175 check
EOF

# Restart HAProxy to apply the changes
sudo service haproxy restart
