#!/usr/bin/env bash
# This script does the following:
# Creates the file "/var/run/myscript.pid" containing its PID
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal

filename="/var/run/myscript.pid"

echo $$ > "$filename"

term_cleanup () {
	echo "I hate the kill command"
	sudo rm "$filename" 
	exit
}

quit_cleanup () {
	sudo rm $filename
	exit
}

while true; do
	trap term_cleanup SIGTERM
	trap quit_cleanup SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
	echo "To infinity and beyond"
	sleep 2
done
