#!/usr/bin/env bash
# This script displays processes containing the word "bash" and their PIDs
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
    if grep -q "bash" "$pid/comm" 2>/dev/null; then
        echo "$(basename "$pid") $(<"$pid/comm")"
    fi
done
