#!/usr/bin/env bash
# This script that displays "To infinity and beyond" indefinitely

handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

