#!/usr/bin/env bash
# This script displays the username, user ID, and home directory from /etc/passwd

while IFS=: read -r username _ userid _ home_directory _; do
    echo "$username:$userid:$home_directory"
done < /etc/passwd
