#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data.

sed -n 's/^\([0-9.]*\).* "\([A-Z]* .* HTTP\/.*\)" \([0-9]*\).*/\1 \3/p' apache-access.log | \
    awk '{count[$1,$2]++} END {for (key in count) print count[key], key}' | \
    sort -nr
