#!/usr/bin/env bash
# This script configures an Ubuntu server and resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

file="/etc/hosts"
backupfile="$HOME/hosts.bkp"

sudo cp "$file" "$backupfile"

sudo sed -i s/127.0.0.1/127.0.0.2/ "$backupfile"
echo "8.8.8.8	facebook.com" >> "$backupfile"

sudo cp -f "$backupfile" "$file"
